//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public class DMXAttribute
{
	public string Name {get;set;}
	public byte Value {get;set;}

	public DMXAttribute (string name)
	{
		Name = name;
		Value = 0;
	}
}

